### ISSUE TITLE
Error on "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by ChirpyTinkerer** [masterofobzene/JDproxygenerator#3]
When I put the command "pip install -r requirements.txt" I got this error:

      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
Failed to build lxml
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lxml)"

**Comment by masterofobzene** [comment]
That issue doesn't seem to be related to this script...  I also didn't have any issues running the script on my end now.

Try to open a CMD on the directory where "requirements.txt" is and re-run the command. I don't understand why you got it running inside C:\Program Files (x86)\Microsoft Visual Studio.. ..

**Comment by ChirpyTinkerer** [comment]
Yes, I change the directory using "cd" , I think automatically it says "C:\Program Files (x86)\Microsoft Visual Studio.. .." because I did not did that.

**Comment by ChirpyTinkerer** [comment]
It also says this: 
xmlXPathInit1g7419bc.c
      C:\Users\my user\AppData\Local\Temp\xmlXPathInit1g7419bc.c(1): fatal error C1083: No se puede abrir el archivo incluir: 'libxml/xpath.h': No such file or directory
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

**Comment by masterofobzene** [comment]
uhmm no you are doing it wrong.

1- Download the zip with the script and unzip it on your **downloads** folder. You should end up with a folder named "JDproxygenerator-main".

2- open a CMD and copy this `cd %UserProfile%\downloads\JDproxygenerator-main`

3- now run `pip install -r requirements.txt`
